# vscode.yml
# App-specific Espanso configuration for Visual Studio Code on macOS

# Activate only when VS Code is the current application
filter_exec: "/Applications/Visual Studio Code\\.app"
# or equivalently (optional alternative)
# filter_class: "com.microsoft.VSCode"

config:
  config:
  backend: clipboard

# Include your usual snippets
extra_includes:
  - "../match/base.yml"
